---
- hosts: localhost
  gather_facts: false
  vars:
    parsers: "{{ query('fileglob', 'cols/*.yml', allow_unsafe=True) }}"
  tasks:
    - include_tasks: test_parser.yml
      loop: "{{ parsers|makelist }}"
      loop_control:
        loop_var: column_defs
