---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: show vlan port all
      set_fact:
        show_vlan_port_all: "{{ lookup('file', 'show_vlan_port_all.txt')|parse_columns('cols/show_vlan_port_all.yml') }}"

    - name: check show vlan port all results
      assert:
        that:
          - show_vlan_port_all.1.interface == '0/2'
          - show_vlan_port_all.1.pvid_configured == '100'
          - show_vlan_port_all.1.pvid_current == '100'
          - show_vlan_port_all.1.accept_frame_types == 'Admit All'
          - show_vlan_port_all.1.ingress_configured == 'Enable'
          - show_vlan_port_all.1.ingress_current == 'Enable'
          - show_vlan_port_all.1.gvrp == 'Disable'
          - show_vlan_port_all.1.priority == '0'
